dsmod user CN=testuser001,OU=Hilden,OU=Zentrale,DC=SV22,DC=local -disabled yes
dsmod user CN=testuser002,OU=Hilden,OU=Zentrale,DC=SV22,DC=local -disabled yes
dsmod user CN=testuser003,OU=Hilden,OU=Zentrale,DC=SV22,DC=local -disabled yes
dsmod user CN=testuser004,OU=Hilden,OU=Zentrale,DC=SV22,DC=local -disabled yes
dsmod user CN=testuser005,OU=Hilden,OU=Zentrale,DC=SV22,DC=local -disabled yes
dsmod user CN=testuser006,OU=Hilden,OU=Zentrale,DC=SV22,DC=local -disabled yes
dsmod user CN=testuser007,OU=Hilden,OU=Zentrale,DC=SV22,DC=local -disabled yes
dsmod user CN=testuser008,OU=Hilden,OU=Zentrale,DC=SV22,DC=local -disabled yes
dsmod user CN=testuser009,OU=Hilden,OU=Zentrale,DC=SV22,DC=local -disabled yes
dsmod user CN=testuser010,OU=Hilden,OU=Zentrale,DC=SV22,DC=local -disabled yes
dsmod user CN=testuser011,OU=Hilden,OU=Zentrale,DC=SV22,DC=local -disabled yes
dsmod user CN=testuser012,OU=Hilden,OU=Zentrale,DC=SV22,DC=local -disabled yes
dsmod user CN=testuser013,OU=Hilden,OU=Zentrale,DC=SV22,DC=local -disabled yes
dsmod user CN=testuser014,OU=Hilden,OU=Zentrale,DC=SV22,DC=local -disabled yes
dsmod user CN=testuser015,OU=Hilden,OU=Zentrale,DC=SV22,DC=local -disabled yes
dsmod user CN=testuser016,OU=Hilden,OU=Zentrale,DC=SV22,DC=local -disabled yes
dsmod user CN=testuser017,OU=Hilden,OU=Zentrale,DC=SV22,DC=local -disabled yes
dsmod user CN=testuser018,OU=Hilden,OU=Zentrale,DC=SV22,DC=local -disabled yes
dsmod user CN=testuser019,OU=Hilden,OU=Zentrale,DC=SV22,DC=local -disabled yes
dsmod user CN=testuser020,OU=Hilden,OU=Zentrale,DC=SV22,DC=local -disabled yes
dsmod user CN=testuser021,OU=Hilden,OU=Zentrale,DC=SV22,DC=local -disabled yes
dsmod user CN=testuser022,OU=Hilden,OU=Zentrale,DC=SV22,DC=local -disabled yes
dsmod user CN=testuser023,OU=Hilden,OU=Zentrale,DC=SV22,DC=local -disabled yes
dsmod user CN=testuser024,OU=Hilden,OU=Zentrale,DC=SV22,DC=local -disabled yes
dsmod user CN=testuser025,OU=Hilden,OU=Zentrale,DC=SV22,DC=local -disabled yes
dsmod user CN=testuser026,OU=Hilden,OU=Zentrale,DC=SV22,DC=local -disabled yes
dsmod user CN=testuser027,OU=Hilden,OU=Zentrale,DC=SV22,DC=local -disabled yes
dsmod user CN=testuser028,OU=Hilden,OU=Zentrale,DC=SV22,DC=local -disabled yes
dsmod user CN=testuser029,OU=Hilden,OU=Zentrale,DC=SV22,DC=local -disabled yes
dsmod user CN=testuser030,OU=Hilden,OU=Zentrale,DC=SV22,DC=local -disabled yes
dsmod user CN=testuser031,OU=Hilden,OU=Zentrale,DC=SV22,DC=local -disabled yes
dsmod user CN=testuser032,OU=Hilden,OU=Zentrale,DC=SV22,DC=local -disabled yes
dsmod user CN=testuser033,OU=Hilden,OU=Zentrale,DC=SV22,DC=local -disabled yes
dsmod user CN=testuser034,OU=Hilden,OU=Zentrale,DC=SV22,DC=local -disabled yes
dsmod user CN=testuser035,OU=Hilden,OU=Zentrale,DC=SV22,DC=local -disabled yes
dsmod user CN=testuser036,OU=Hilden,OU=Zentrale,DC=SV22,DC=local -disabled yes
dsmod user CN=testuser037,OU=Hilden,OU=Zentrale,DC=SV22,DC=local -disabled yes
dsmod user CN=testuser038,OU=Hilden,OU=Zentrale,DC=SV22,DC=local -disabled yes
dsmod user CN=testuser039,OU=Hilden,OU=Zentrale,DC=SV22,DC=local -disabled yes
dsmod user CN=testuser040,OU=Hilden,OU=Zentrale,DC=SV22,DC=local -disabled yes
dsmod user CN=testuser041,OU=Hilden,OU=Zentrale,DC=SV22,DC=local -disabled yes
dsmod user CN=testuser042,OU=Hilden,OU=Zentrale,DC=SV22,DC=local -disabled yes
dsmod user CN=testuser043,OU=Hilden,OU=Zentrale,DC=SV22,DC=local -disabled yes
dsmod user CN=testuser044,OU=Hilden,OU=Zentrale,DC=SV22,DC=local -disabled yes
dsmod user CN=testuser045,OU=Hilden,OU=Zentrale,DC=SV22,DC=local -disabled yes
dsmod user CN=testuser046,OU=Hilden,OU=Zentrale,DC=SV22,DC=local -disabled yes
dsmod user CN=testuser047,OU=Hilden,OU=Zentrale,DC=SV22,DC=local -disabled yes
dsmod user CN=testuser048,OU=Hilden,OU=Zentrale,DC=SV22,DC=local -disabled yes
dsmod user CN=testuser049,OU=Hilden,OU=Zentrale,DC=SV22,DC=local -disabled yes
dsmod user CN=testuser050,OU=Hilden,OU=Zentrale,DC=SV22,DC=local -disabled yes
dsmod user CN=testuser051,OU=Hilden,OU=Zentrale,DC=SV22,DC=local -disabled yes
dsmod user CN=testuser052,OU=Hilden,OU=Zentrale,DC=SV22,DC=local -disabled yes
dsmod user CN=testuser053,OU=Hilden,OU=Zentrale,DC=SV22,DC=local -disabled yes
dsmod user CN=testuser054,OU=Hilden,OU=Zentrale,DC=SV22,DC=local -disabled yes
dsmod user CN=testuser055,OU=Hilden,OU=Zentrale,DC=SV22,DC=local -disabled yes
dsmod user CN=testuser056,OU=Hilden,OU=Zentrale,DC=SV22,DC=local -disabled yes
dsmod user CN=testuser057,OU=Hilden,OU=Zentrale,DC=SV22,DC=local -disabled yes
dsmod user CN=testuser058,OU=Hilden,OU=Zentrale,DC=SV22,DC=local -disabled yes
dsmod user CN=testuser059,OU=Hilden,OU=Zentrale,DC=SV22,DC=local -disabled yes
dsmod user CN=testuser060,OU=Hilden,OU=Zentrale,DC=SV22,DC=local -disabled yes
dsmod user CN=testuser061,OU=Hilden,OU=Zentrale,DC=SV22,DC=local -disabled yes
dsmod user CN=testuser062,OU=Hilden,OU=Zentrale,DC=SV22,DC=local -disabled yes
dsmod user CN=testuser063,OU=Hilden,OU=Zentrale,DC=SV22,DC=local -disabled yes
dsmod user CN=testuser064,OU=Hilden,OU=Zentrale,DC=SV22,DC=local -disabled yes
dsmod user CN=testuser065,OU=Hilden,OU=Zentrale,DC=SV22,DC=local -disabled yes
dsmod user CN=testuser066,OU=Hilden,OU=Zentrale,DC=SV22,DC=local -disabled yes
dsmod user CN=testuser067,OU=Hilden,OU=Zentrale,DC=SV22,DC=local -disabled yes
dsmod user CN=testuser068,OU=Hilden,OU=Zentrale,DC=SV22,DC=local -disabled yes
dsmod user CN=testuser069,OU=Hilden,OU=Zentrale,DC=SV22,DC=local -disabled yes
dsmod user CN=testuser070,OU=Hilden,OU=Zentrale,DC=SV22,DC=local -disabled yes
dsmod user CN=testuser071,OU=Hilden,OU=Zentrale,DC=SV22,DC=local -disabled yes
dsmod user CN=testuser072,OU=Hilden,OU=Zentrale,DC=SV22,DC=local -disabled yes
dsmod user CN=testuser073,OU=Hilden,OU=Zentrale,DC=SV22,DC=local -disabled yes
dsmod user CN=testuser074,OU=Hilden,OU=Zentrale,DC=SV22,DC=local -disabled yes
dsmod user CN=testuser075,OU=Hilden,OU=Zentrale,DC=SV22,DC=local -disabled yes
dsmod user CN=testuser076,OU=Hilden,OU=Zentrale,DC=SV22,DC=local -disabled yes
dsmod user CN=testuser077,OU=Hilden,OU=Zentrale,DC=SV22,DC=local -disabled yes
dsmod user CN=testuser078,OU=Hilden,OU=Zentrale,DC=SV22,DC=local -disabled yes
dsmod user CN=testuser079,OU=Hilden,OU=Zentrale,DC=SV22,DC=local -disabled yes
dsmod user CN=testuser080,OU=Hilden,OU=Zentrale,DC=SV22,DC=local -disabled yes
dsmod user CN=testuser081,OU=Hilden,OU=Zentrale,DC=SV22,DC=local -disabled yes
dsmod user CN=testuser082,OU=Hilden,OU=Zentrale,DC=SV22,DC=local -disabled yes
dsmod user CN=testuser083,OU=Hilden,OU=Zentrale,DC=SV22,DC=local -disabled yes
dsmod user CN=testuser084,OU=Hilden,OU=Zentrale,DC=SV22,DC=local -disabled yes
dsmod user CN=testuser085,OU=Hilden,OU=Zentrale,DC=SV22,DC=local -disabled yes
dsmod user CN=testuser086,OU=Hilden,OU=Zentrale,DC=SV22,DC=local -disabled yes
dsmod user CN=testuser087,OU=Hilden,OU=Zentrale,DC=SV22,DC=local -disabled yes
dsmod user CN=testuser088,OU=Hilden,OU=Zentrale,DC=SV22,DC=local -disabled yes
dsmod user CN=testuser089,OU=Hilden,OU=Zentrale,DC=SV22,DC=local -disabled yes
dsmod user CN=testuser090,OU=Hilden,OU=Zentrale,DC=SV22,DC=local -disabled yes
dsmod user CN=testuser091,OU=Hilden,OU=Zentrale,DC=SV22,DC=local -disabled yes
dsmod user CN=testuser092,OU=Hilden,OU=Zentrale,DC=SV22,DC=local -disabled yes
dsmod user CN=testuser093,OU=Hilden,OU=Zentrale,DC=SV22,DC=local -disabled yes
dsmod user CN=testuser094,OU=Hilden,OU=Zentrale,DC=SV22,DC=local -disabled yes
dsmod user CN=testuser095,OU=Hilden,OU=Zentrale,DC=SV22,DC=local -disabled yes
dsmod user CN=testuser096,OU=Hilden,OU=Zentrale,DC=SV22,DC=local -disabled yes
dsmod user CN=testuser097,OU=Hilden,OU=Zentrale,DC=SV22,DC=local -disabled yes
dsmod user CN=testuser098,OU=Hilden,OU=Zentrale,DC=SV22,DC=local -disabled yes
dsmod user CN=testuser099,OU=Hilden,OU=Zentrale,DC=SV22,DC=local -disabled yes
dsmod user CN=testuser100,OU=Hilden,OU=Zentrale,DC=SV22,DC=local -disabled yes
